version: '3.9'

networks:
  carsnetwork:
    external: true

services:
  
  mongo:
    image: mongo
    container_name: 'mongo'
    restart: always
    command: mongod --port 27018
    ports:
     - '27018:27018'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 55financial
    networks:
      - carsnetwork

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=passw0rd1
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - carsnetwork
        
  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: 'redis'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - carsnetwork

        
  crawler-api:
    container_name: 'crawler-api'
    image: ${REGISTRY:-carscrawler}/carscrawler.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/CarsCrawler/CarsCrawler.API/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - '5010:80'
    networks:
      - carsnetwork

  
  crawler-consumers:
    image: ${REGISTRY:-carscrawler}/carscrawler.consumers:${PLATFORM:-windows}-${TAG:-latest}
    container_name: 'crawler-consumer'
    build:
      context: .
      dockerfile: Services/CarsCrawler/CarsCrawler.Consumers/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - carsnetwork

volumes:
  redis_data:
    driver: local

    